#!/usr/bin/env python

Import("env")
Import("env_modules")

sources = [
    "thirdparty/src/clippable_mesh.cpp",
    "thirdparty/src/hydro_rigid_body.cpp",
    "thirdparty/src/register_types.cpp",
    "thirdparty/src/water_area.cpp",
    "thirdparty/src/watercraft_ballast.cpp",
    "thirdparty/src/watercraft_propulsion.cpp",
    "thirdparty/src/watercraft_rudder.cpp",
]
env_hydro = env_modules.Clone()
env_hydro.add_source_files(env.modules_sources, sources)

if env.editor_build:
    env_hydro.add_source_files(env.modules_sources, "thirdparty/editor/*.cpp")
